import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans} from "next/font/google";
import { Button } from "@/components/ui/button";
import { authorise } from "@/utils/authorisationLogic"
import { signOut, getTokens, TokenType } from "@/utils/token";

const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(){
  

  return (
    
    <div>
      <h1>main page</h1>
        
      </div>
      
  )

}
