import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans} from "next/font/google";
import { Button } from "@/components/ui/button";
import { authorise } from "@/utils/authorisationLogic"
import { signOut, getTokens, TokenType } from "@/utils/token";

const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(){
  

  return (
    
    <div
      className={cn(
        
        "min-h-screen bg-[url('/1646371322_10-kartinkin-net-p-kartinki-pro-uchebu-10.jpg')] font-sans antialiased flex flex-col justify-center items-center gap-4",
        fontSans.variable
      )}
      >
         <div className="absolute top-0 left-0 w-1/2, h-1/2">
          <img
            src="/эмблема.png" // Убедитесь, что путь к изображению правильный
            alt="Эмблема"
            className="w-24 h-24"
          />
        </div>
       <div className="absolute top-0 right-0 h-full w-1/4 bg-purple-700"></div>
       <div className="absolute top-0 right-0 h-full w-1/4 z-20 flex flex-col justify-start items-center text-white text-xl font-bold p-5">
        <p className="text-center">Добро пожаловать на онлайн платформу для обучения и преподавания. Здесь вы сможете как освоить новые направления и профессии, так и быть преподавателем и передовать свои знания другим людям, а также многое другое. Присоединяйся!</p>
        <div className="mt-auto">
          <img
            src="/photo-in-article-risunki-i-kartinki-dlja-srisovki-04-kotiki-01-1024x1024-1.jpg"
            alt="Additional Image"
            className="w-full"
          />
      </div>
      </div>
        <p><Button className="hover:bg-green-300" 
        onClick={authorise}
        >
          Authorization</Button></p>
        <p><Button className="hover:bg-green-300">Create account</Button></p> 
        <p><Button className="hover:bg-green-300" onClick={signOut}>Logout</Button></p>  
        
      </div>
      
  )

}
