services:
  postgres:
    container_name: "user-service"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=userservicedb'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=userservice'
    ports:
      - '6432:5432'
